---
- name: Installation install software-properties-common
  apt: 
    name: software-properties-common
  when: ansible_distribution == "Ubuntu"

- name: Repo PHP 7.4
  apt_repository:
    repo: ppa:ondrej/php
  when: ansible_distribution == "Ubuntu"
   
- name: Updating the repo
  apt: 
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Installation "{{ php_version }}"
  apt: 
    name: "php{{ php_version }}"
    state: present
  when: ansible_distribution == "Ubuntu"
  
- name: Install lamp stack
  apt:
    pkg:
      - "php{{ php_version }}"
      - "php{{ php_version }}-apcu"
      - "php{{ php_version }}-cli"
      - "php{{ php_version }}-common"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-dev"
      - "php{{ php_version }}-fpm"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-imap"
      - "php{{ php_version }}-json"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-opcache"
      - "php{{ php_version }}-sqlite3"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-yaml"
    state: present
    update_cache: yes 
    when: ansible_distribution == "Ubuntu"

