---
- hosts: all
  become: true
  vars_files:
    - "vars/default.yml"
  roles:
    - { role: geerlingguy.php }
  tasks:
    
    # Create user
    - name: Create user for OS
      user:
        name: "{{ web_user }}"
        password: "{{ web_user_password | password_hash('sha512')}}"
        shell: /bin/bash
        state: present

    # Creates directorys

    - name: Create a directory {{ domain_name }} in "sites" if it does not exist
      file:
        path: "{{ path_project }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0755'

    - name: Create a directory {{ domain_name }} in "shared" if it does not exist
      file:
        path: "{{ path_shared_project }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0755'


    # Install Utility software

    - name: Install PIP, PyMysql
      apt: 
        name: "{{ item }}"
        state: latest
      loop:
        - python3-pip
        - python3-pymysql

    # Install MariaDB
    - name: Install MariaDB
      apt: 
        name: mariadb-server 
        state: latest 
        update_cache: yes

    - name: Start MariaDB
      service:
        name: mysql
        state: started

    - name: Add sql-mode in my.cnf
      command: echo 'sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"' >> /etc/mysql/my.cnf
      ignore_errors: yes

    - name: Restart mariadb
      service:
        name: mariadb
        state: restarted  

    # Setting mysql_secure_installation
    - name: Setting mysql_secure_installation
      command: echo "{{ mysql_root_password }}\n n\n n\n y\n y\n y\n y\n" | sudo mysql_secure_installation
    
    # Setting database
    - name: Create database
      mysql_db:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        name: "{{ mysql_name_db }}"
        state: present
    
    - name: Create user for database
      mysql_user: 
        login_user: root
        login_password: "{{ mysql_root_password }}"
        login_unix_socket: /run/mysqld/mysqld.sock
        name: "{{ mysql_name_user }}"
        password: "{{ mysql_password_user }}"
        host: localhost
        priv: "{{ mysql_name_db }}.*:ALL"
        state: present

    # Install PHP
    
    - name: Install PHP modules
      apt:
        name: "{{ php_packages }}"
        update_cache: yes

    - name: Create a directory for php session if it does not exist
      file:
        path: "{{ php_session_path }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0755'

    # Config php.ini and user config

    - name: Template bitrix.ini
      ansible.builtin.template:
        src: "{{ php_ini }}"
        dest: /etc/php/{{ php_version }}/mods-available/local.ini

    - name: Template web.conf
      ansible.builtin.template:
        src: "{{ php_conf }}"
        dest: /etc/php/{{ php_version }}/fpm/pool.d/web.conf

    - name: Renamed www.conf to www.conf_default
      command: mv /etc/php/{{ php_version }}/fpm/pool.d/www.conf /etc/php/7.4/fpm/pool.d/www.conf_default
      ignore_errors: yes

    - name: Create symlink for bitrix.ini in fpm
      file:
        src: /etc/php/{{ php_version }}/mods-available/local.ini
        dest: /etc/php/{{ php_version }}/fpm/conf.d/50-bitrix.ini
        state: link

    - name: Create symlink for bitrix.ini in cli
      file:
        src: /etc/php/{{ php_version }}/mods-available/local.ini
        dest: /etc/php/{{ php_version }}/cli/conf.d/50-bitrix.ini
        state: link

    - name: Restart service php-fpm
      service:
        name: php{{ php_version }}-fpm
        state: restarted

    # Install Nginx
    - name: Install nginx
      apt: 
        name: nginx
        state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started

    - name: Delete default.conf
      file: 
        state: absent
        path: "/etc/nginx/sites-enabled/default"

    - name: Delete default.conf
      file: 
        state: absent
        path: "/etc/nginx/sites-available/default"

    - name: Template the nginx config file and restart nginx
      template:
        src: "{{nginx_config}}"
        dest: /etc/nginx/sites-available/{{ domain_name }}

    - name: Create symlink
      file:
        src: /etc/nginx/sites-available/{{ domain_name }}
        dest: /etc/nginx/sites-enabled/{{ domain_name }}
        state: link

    - name: Change web user  for server
      ansible.builtin.replace:
        path: /etc/nginx/nginx.conf
        regexp: 'user www-data;'
        replace: 'user web;'
    
    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    # Install and setings certboot
    - name: "Install cerboot and python3-certbot-nginx"
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - certbot
        - python3-certbot-nginx

    - name: Generateing certificate with subdomens
      command:  sudo certbot --non-interactive --agree-tos -m "{{ email_certboot }}" --nginx -d "{{ domain_name }}" {% for host in list_subdomens %} --nginx -d {{ host }} {% endfor %}
      when: "{{ list_subdomens }}"

    - name: Generateing certificate no with subdomens
      command:  sudo certbot --non-interactive --agree-tos -m "{{ email_certboot }}" --nginx -d "{{ domain_name }}"
    
    
