---
- name: Set the correct opcache filename (Ubuntu/Debian).
  set_fact:
    php_opcache_conf_filename: "10-opcache.ini"

- name: Ensure dirmngr is installed (gnupg dependency).
  apt:
    name: dirmngr
    state: present

- name: Add repository for PHP versions (Ubuntu).
  apt_repository: repo='ppa:ondrej/php'
  when: ansible_distribution == "Ubuntu"

- name: Installation PHP
  apt: 
    name: php{{ php_version }} 
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install lamp stack
  apt:
    pkg:
      - php{{ php_version }}-mysql
      - php{{ php_version }}-curl
      - php{{ php_version }}-bcmath
      - php{{ php_version }}-json
      - php{{ php_version }}-xsl
      - php{{ php_version }}-gd
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-zip
      - php{{ php_version }}-xml
      - php{{ php_version }}-readline
      - php{{ php_version }}-fpm
      - php{{ php_version }}-intl
    state: present
    update_cache: yes


- name: Purge PHP version packages (besides the currently chosen php_version).
  apt:
    name: "{{ php_versions_debian | reject('search', 'php' ~ php_version) | list }}"
    state: absent
    purge: true
    force: true
  register: php_version_purge

- name: Also purge php-common package if any versions were just purged.
  apt:
    name: php-common
    state: absent
    purge: true
    force: true
  when: php_version_purge.changed | bool
