---
# Configs
nginx_config: ./configs/nginx/bitrix.conf.j2
php_conf: ./configs/php/web.conf
php_ini: ./configs/php/bitrix.ini

# Linux parameters
web_user: web
web_user_password: test

# MySQL parameters
mysql_root_password: test
mysql_name_db: test_ansible
mysql_name_user: web
mysql_password_user: test

# Nginx parameters
domain_name: test.ru
path_project: /var/www/web/sites/{{ domain_name }}
path_shared_project: /var/www/web/shared/{{ domain_name }}